services:
  - type: web
    name: resume-analyzer-frontend
    env: static
    staticPublishPath: ./frontend/dist
    routes:
      - path: /*
        destination: /index.html

  - type: web
    name: resume-analyzer-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir backend src.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5